</main>
<footer>
	<ul class="nav justify-content-center border-top py-2 mt-4 text-center">
		<li class="nav-item"><a href="#" class="nav-link text-muted">CHPP</a></li>
		<li class="nav-item"><a href="#" class="nav-link text-muted">Forum</a></li>
		<li class="nav-item"><a href="#" class="nav-link text-muted">Source code</a></li>
	</ul>
</footer>
<script type="text/javascript">
	function switchTheme(theme) {
		document.querySelector('html').setAttribute('data-bs-theme', theme);
	}
	const colorMode = window.matchMedia('(prefers-color-scheme: dark)');
	switchTheme(colorMode.matches ? 'dark' : 'light');
	colorMode.addEventListener('change', c => {
		switchTheme(c.matches ? 'dark' : 'light');
	});
</script>
</body>
</html>
