<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="A match predictor for Hattrick">
	<title><?= $title ? $title . ' · IMP' : 'IMP: Match Predictor' ?></title>
	<script src="/imp/binomial.js" type="text/javascript"></script>
	<script src="/imp/form.js" type="text/javascript"></script>
	<script src="/imp/predictor.js" type="text/javascript"></script>
	<script src="/imp/ratings.js" type="text/javascript"></script>
	<link href="/res/bootstrap.min.css" rel="stylesheet">
	<link href="/res/style.css" rel="stylesheet">
	<link href="/res/favicon.svg" rel="icon" type="image/svg+xml">
</head>
<body>
<header class="navbar navbar-light border-bottom">
	<nav class="container">
		<a href="/" class="navbar-brand"><img src="/res/favicon.svg" width="32" class="me-2 align-top">IMP</a>
		<div class="navbar-nav flex-row flex-grow-1">
<?php
if ($_SESSION['accessToken']) {
	echo '<a href="/myteam" class="nav-link active">My Team</a>';
}
?>
		</div>
<?php
if ($_SESSION['accessToken']) {
	echo '<a href="/logout" role="button" class="btn btn-inverted">Log out</a>';
} else {
	echo '<a href="/login" role="button" class="btn btn-inverted">Sign in</a>';
}
?>
	</nav>
</header>
<main class="container">
