<?php
const matchTypeIcons = [
	100 => 'medal',
	200 => 'medal',
	311 => 'cup',
	321 => 'cup_hollow',
	322 => 'cup_hollow',
	323 => 'cup_hollow',
	331 => 'cup_hollow',
	400 => 'flag',
	500 => 'flag',
	700 => 'cup',
	800 => 'flag',
	900 => 'flag'
];

function matchItem($match, $teamName) {
	$matchDate = date_create($match->MatchDate)->format('j/n');
	$matchType = $match->MatchType . $match->CupLevel . $match->CupLevelIndex;
	if ($match->HomeTeam->HomeTeamName->__toString() == $teamName) {
		return [
			'date' => $matchDate,
			'type' => getTranslation('teamMatchType' . $matchType),
			'icon' => matchTypeIcons[$matchType],
			'ground' => getTranslation('teamGroundHome'),
			'teamName' => htmlspecialchars($match->HomeTeam->HomeTeamName),
			'teamId' => $match->HomeTeam->HomeTeamID,
			'oppName' => htmlspecialchars($match->AwayTeam->AwayTeamName),
			'oppId' => $match->AwayTeam->AwayTeamID,
			'isHome' => 'true'
		];
	} else {
		return [
			'date' => $matchDate,
			'type' => getTranslation('teamMatchType' . $matchType),
			'icon' => matchTypeIcons[$matchType],
			'ground' => getTranslation('teamGroundAway'),
			'teamName' => htmlspecialchars($match->AwayTeam->AwayTeamName),
			'teamId' => $match->AwayTeam->AwayTeamID,
			'oppName' => htmlspecialchars($match->HomeTeam->HomeTeamName),
			'oppId' => $match->HomeTeam->HomeTeamID,
			'isHome' => 'false'
		];
	}
}
?>
<h3><?= $title ?></h3>
<div class="table-responsive">
	<table class="table align-middle" id="matches">
<?php
foreach($matches->Team->MatchList->children() as $m) {
	if ($m->SourceSystem == 'Hattrick' and $m->Status != 'UPCOMING') {
		$match = matchItem($m, $title);
		echo '<tr match-id="' . $m->MatchID . '" is-home="' . $match['isHome'] . '">
			<td class="text-center" title="' . $m->MatchDate . '">' . $match['date']. '</td>
			<td title="' . $match['type'] . '">
				<img src="/res/img/match/' . $match['icon'] . '.svg" width="16">
			</td>
			<td class="text-center">' . $match['ground'] . '</td>
			<td width="99%">' . $match['oppName'] . '</td>
			<td class="text-center"></td>
			<td class="text-center"></td>
			<td class="text-center"></td>
			<td>
				<button class="btn btn-inverted p-2"
					title="' . getTranslation('teamSaveAlt') . '"
					onclick="IMP.chpp.saveMatchRatings(' . $m->MatchID . ', ' . $match['isHome'] . ')">
					<img src="/res/img/save.svg" width="24">
				</button>
			</td>
		</tr>';
	}
}
?>
	</table>
</div>
<h3><?= getTranslation('teamNextMatches'); ?></h3>
<table class="table table-hover">
<?php
foreach($matches->Team->MatchList->children() as $m) {
	if ($m->SourceSystem == 'Hattrick' and $m->Status == 'UPCOMING') {
		$match = matchItem($m, $title);
		echo '<tr role="button" onclick="window.location = \'/team/' . $match['oppId'] . '\'">
			<td class="text-center" title="' . $m->MatchDate . '">' . $match['date'] . '</td>
			<td title="' . $match['type'] . '">
				<img src="/res/img/match/' . $match['icon'] . '.svg" width="16">
			</td>
			<td width="99%">' . $match['oppName'] . '</td>
			<td>→</td>
		</tr>';
	}
}
?>
</table>
<div class="float-md-start">
	<div class="input-group">
		<input type="text" class="form-control" name="team_id" placeholder="TeamID"
		onkeyup="if (event.key == 'Enter') window.location = '/team/' + this.value">
		<button class="btn btn-outline rounded-end" type="button"
		onclick="window.location = '/team/' + document.querySelector('[name=team_id]').value">→</button>
	</div>
</div>
<script type="text/javascript">
	// FIXME
	let translations = {
		tactics: [
			'',
			'<?= getTranslation('teamTacticShort1') ?>',
			'<?= getTranslation('teamTacticShort2') ?>',
			'<?= getTranslation('teamTacticShort3') ?>',
			'<?= getTranslation('teamTacticShort4') ?>',
			'',
			'',
			'<?= getTranslation('teamTacticShort7') ?>',
			'<?= getTranslation('teamTacticShort8') ?>'
		],
		derby: '<?= getTranslation('teamGroundDerby') ?>',
		neutral: '<?= getTranslation('teamGroundNeutral') ?>'
	};
	document.onload = IMP.chpp.importMatchesRatings(translations);
</script>
